name: C Code Convention CI

on: [push]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - name: check ansi
        run: find action_test/ -name *.c -exec gcc -Wall -Wextra -pedantic -ansi -c {} \;
