name: C Code Convention CI

on:
  push:
    paths-ignore: "src/*"

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
        - name: cppcheck
          uses: deep5050/cppcheck-action@main
          
        - name: code check
          uses: ./
          with:
            enable: all
            force_language: c
            force: enable
            max_ctu_depth: 4
            std: c11
