name: C Code Convention CI

on:
  push:
    paths-ignore: "src/*"

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
        - name: cppcheck
          uses: deep5050/cppcheck-action@main
          
        - name: cppcheck
          uses: ./
          with:
            check_library: disable
            skip_preprocessor: disable
            enable: all #performance,portability,warning
            exclude_check: ./__tests__/exclude/
            inconclusive: disable
            inline_suppression: disable
            force_language: c
            force: enable
            max_ctu_depth: 12
            platform: disable
            #std: c11
            output_file: ./CppCheckReport.txt
            other_options: --bug-hunting --verbose --std=c
            
        - name: publish report    
          uses: mikeal/publish-to-github-action@master
          env:
            BRANCH_NAME: 'main' # your branch name goes here
            
        - name: check
          run : cppcheck --enable=all --inconclusive --std=c++17 main.c
