name: C Code Convention CI

on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
          
        
      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          BRANCH_NAME: 'main'
