name: C Code Convention CI

on:
  push:
    paths-ignore: "src/*"

jobs:
    c-linter:
      name: c-linter
      runs-on: ubuntu-latest
      steps:
        - name: c-linter
          uses: ArtificialAmateur/cpp-linter-action@maste
