name: C Code Convention CI

on: [push]

jobs:
  build-and-test:
      runs-on: ubuntu-18.04
      steps:
      - name: check ansi
        shell: bash
        run: echo find ./ -name *.c -exec gcc -Wall -Wextra -pedantic -ansi -c {} \;
