name: C Code Convention CI

on:
  push:
    paths-ignore: "src/*"

jobs:
  build-and-test:
      runs-on: ubuntu-18.04
      steps:
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        with:
          style: file
          files-changed-only: false
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        run: |
          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
